name: multi_ppo_pytorch
channels:
  - numba
  - pytorch
  - conda-forge
dependencies:
  - python
  - pytorch
  - scipy
  - gym=0.21.0
  - numba
  - black
  - swig
  - numpy
  - matplotlib
  - pytorch-lightning
  - cudatoolkit
  - sphinx
  - pip
  - ray
  - joblib
  - mpi4py
  - psutil
  - pip:
      - -e ./gym_rad_search
      - sphinx-rtd-theme
