name: RAD-TEAM
channels:
  - numba
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - gymnasium
  # Rendering
  - matplotlib
  - pygame=2.1.*
  # Docs
  - sphinx
  - sphinxcontrib-spelling
  - sphinx-autobuild
  - sphinx-rtd-theme
  - sphinx-copybutton
  # Testing
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  # Linting/Type checking
  - mypy
  - ruff
  - black
  # Setup
  - setuptools
  - pip
  - pip:
    - -e .
    # Custom environments need this seperately
    - -e src/envs