name: multi_ppo_pytorch
channels:
  - numba
  - pytorch
  - conda-forge
dependencies:
  - python
  - pytorch
  - scipy
  - gym
  - numba
  - black
  - swig
  - numpy
  - matplotlib
  - pytorch-lightning
  - cudatoolkit
  - pip
  - pip:
      - -e ../../gym_rad_search
      - -U ray
