name: ppo_rad_2
channels:
  - numba
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.11
  - scipy
  - gym
  - numba
  - black
  - swig
  - cudatoolkit
  - gym
  - numpy
  - matplotlib
  - pip
  - pip:
      - -e ../../gym_rad_search
      - -U ray

