# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    env:
      TERM: xterm-256color
      FORCE_COLOR: 1

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


      - name: Lint with ruff
        run: |
          make lint

      - name: Check codestyle
        run: |
          make check-codestyle
      - name: Type check
        run: |
          make type

      - name: Install environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yml
          environment-name: rad-team
          init-shell: >-
            bash
            powershell
          cache-environment: true

      - name: Test with pytest
        shell: micromamba-shell {0}
        run: |
          make pytest
