# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    env:
      TERM: xterm-256color
      FORCE_COLOR: 1

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: environment.yml
          environment-name: rad-team

      - name: Lint with ruff
        run: |
          make lint

      - name: Check codestyle
        run: |
          make check-codestyle
      - name: Type check
        run: |
          make type
      - name: Test with pytest
        run: |
          make pytest
